Initial automated deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy App
+name: POC-10 EC2 CI/CD Deploy
 
 on:
   push:
@@ -10,14 +10,48 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      # Step 1 - Checkout repo
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-    - name: Deploy to EC2
-      run: |
-        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
-          sudo rm -rf /home/ubuntu/app &&
-          mkdir /home/ubuntu/app &&
-          exit
-        "
-        scp -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/app/
-        ssh ubuntu@${{ secrets.EC2_IP }} "bash /home/ubuntu/app/deploy.sh"
+      # Step 2 - SSH into EC2 and deploy
+      - name: Deploy to EC2 via SSH
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          port: 22
+          script: |
+            echo "Connected to EC2"
+
+            # Create a app dir, if exists mkdir does nothing like no error
+            sudo mkdir -p /var/www/poc10-app
+
+            # CHOWN of that app
+            sudo chown ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /var/www/poc10-app
+
+            # Go to the app dir
+            cd /var/www/poc10-app || exit 1
+
+
+            # check if .git is there in the app
+            if [ -d .git ]; then
+                echo "Git repo found!"
+                echo "Pulling latest changes"
+
+                git pull
+            else
+                echo "Git repo not found!"
+                echo "Cloning the repo"
+
+                git clone "https://github.com/arjunsharma6622/poc10-aws-app" .
+            fi
+
+            echo "Installing npm..."
+            npm i
+
+            echo "Starting/Reloading PM2"
+            pm2 start ecosystem.config.js || pm2 reload ecosystem.config.js
+
+            echo "Deployment Completed Succesfully"
